apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu-ssh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-ssh
    spec:
      containers:
      - name: ubuntu-ssh
        image: zhaoqin/ubuntu-ssh:16.04
        imagePullPolicy: Always
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh
  labels:
    app: ubuntu-ssh
spec:
  type: NodePort
  ports:
  - port: 22
    nodePort: 30022
    name: ssh
  selector:
    app: ubuntu-ssh
---
